spring:
  application:
    name: discovery
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:./config/,file:./discovery/config,file:./05_Microservice_Organization/discovery/config

eureka:
  dashboard:
    path: /dashboard/
    enabled: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8888
